services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ../espacos-publicitarios-frontend-main/espacos-publicitarios-frontend
    container_name: frontend
    ports:
      - "3000:80"
